## **NUMPY TUTORIAL**

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([[1,2,3],[2,4,5],[2,3,6]])
arr2=np.array([[2,3,4],[8,5,4],[5,6,8]])

**Sum & Difference of arrays in numpy**

In [ ]:
sum_array=arr1+arr2
print(sum_array)

[[ 3  5  7]
 [10  9  9]
 [ 7  9 14]]


In [ ]:
print(arr1-arr2)

[[-1 -1 -1]
 [-6 -1  1]
 [-3 -3 -2]]


In [ ]:
print(np.subtract(arr1,arr2))

[[-1 -1 -1]
 [-6 -1  1]
 [-3 -3 -2]]


**Adding all the elements row wise and column wise in an array**

In [ ]:
print(np.sum(arr1))

28


**Dot Multiplication**

In [ ]:
mnp=arr1@arr2
print(mnp)

[[33 31 36]
 [61 56 64]
 [58 57 68]]


In [ ]:
print(np.dot(arr1,arr2))

[[33 31 36]
 [61 56 64]
 [58 57 68]]


**Element by element multiplication**

In [ ]:
print(arr1*arr2)

[[ 2  6 12]
 [16 20 20]
 [10 18 48]]


In [ ]:
maul=np.multiply(arr1,arr2)
print(maul)

[[ 2  6 12]
 [16 20 20]
 [10 18 48]]


**Division in Numpy**

In [ ]:
div=np.divide(arr1,2)
print(div)

[[0.5 1.  1.5]
 [1.  2.  2.5]
 [1.  1.5 3. ]]


In [ ]:
 print(np.floor_divide(arr1,2))

[[0 1 1]
 [1 2 2]
 [1 1 3]]


**Math Class in NUMPY**

In [ ]:
print(np.math.sqrt(36))

6.0


### **Random Array Creation in Numpy**

**Generating Standard Normal arrays**

In [ ]:
random_arr=np.random.standard_normal((3,4)) #generated array with 3 rows 4 column
print(random_arr)

[[-0.09611259  0.25852173 -0.10209424 -1.86195921]
 [-1.53662538 -0.01490305  1.26916288 -0.20704708]
 [ 0.441732    1.66031259 -0.33957158  1.18771714]]


**Generating Uniform Distributed array**

In [ ]:
random_arr2=np.random.uniform(1,12,(3,4)) #generated array with 3 rows & 4 columns and number ranging from 1 to 12 
print(random_arr2)

[[ 1.12242022 11.06355393  9.92549503  7.89921582]
 [ 2.02812244  3.4625705   7.36749588 10.33933849]
 [ 4.25927721  6.64920014 11.72555751  4.32149599]]


**Generating Array of different datatypes**

In [ ]:
eg1=np.random.randint(1,10,(4,4)) #Generated an array with integer number
print(eg1)

[[5 8 9 8]
 [8 6 2 4]
 [2 7 8 5]
 [9 9 5 4]]


In [ ]:
ze=np.zeros((3,4))
print(ze)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ek=np.ones((3,4))
print(ek)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.random.rand())

0.5269382362493391


**Creating Logical table in Numpy**

In [ ]:
Random_Ar=np.random.randint(1,250,(2,5))
filter_ar=np.logical_and(Random_Ar>30,Random_Ar<50)

In [ ]:
print(filter_ar)

[[False False  True False False]
 [False False False False False]]


In [ ]:
frandom_ar=np.logical_or(Random_Ar>30,Random_Ar<50)
print(frandom_ar)

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


**Statistics in Numpy**

In [ ]:
dataset=np.array([1,3,4,5,7,9])
mean_dat=np.mean(dataset)
print(mean_dat)

4.833333333333333


In [ ]:
median_dat=np.median(dataset)
print(median_dat)

4.5


In [ ]:
var_dat=np.var(dataset)
print(var_dat)

6.805555555555556


In [ ]:
sd_dat=np.std(dataset)
sd_dat1=np.math.sqrt(var_dat)
print(sd_dat)
print(sd_dat1)

2.608745973749755
2.608745973749755


In [ ]:
var_arr1=np.var(arr1,axis=1) #calculates variance for each row of array and shows its variance
var_arr1col=np.var(arr1,axis=0) # calculates the variance for each column values)
print(var_arr1)
print(var_arr1col)

[0.66666667 1.55555556 2.88888889]
[0.22222222 0.66666667 1.55555556]


## **Pandas Library**

In [ ]:
import pandas as pd

**Creating a small dataframe**

In [ ]:
age=pd.Series([10,20,30,40],index=['age1','age2','age3','age4'])

In [ ]:
print(age)

age1    10
age2    20
age3    30
age4    40
dtype: int64


Constraints for displaying specific data from dataframe

In [ ]:
age.age3

30

In [ ]:
Filtered_age=age[age>20]
print(Filtered_age)

age3    30
age4    40
dtype: int64


Calling values %Indexes

In [ ]:
print(age.values)
print(age.index)

[10 20 30 40]
Index(['age1', 'age2', 'age3', 'age4'], dtype='object')


In [ ]:
age.index=['a1','a2','a3','a4']
print(age.index)

Index(['a1', 'a2', 'a3', 'a4'], dtype='object')


**DataFrames**

In [ ]:
df=np.array([[20,10,8],[25,8,10],[27,5,3],[30,9,7]])
dat_set=pd.DataFrame(df)
print(dat_set)

    0   1   2
0  20  10   8
1  25   8  10
2  27   5   3
3  30   9   7


**Setting row and column names**

In [ ]:
dat_set1=pd.DataFrame(df,index=['s1','s2','s3','s4'],columns=['Sub1','Sub2','Sub3'])
print(dat_set1)

    Sub1  Sub2  Sub3
s1    20    10     8
s2    25     8    10
s3    27     5     3
s4    30     9     7


Adding dataset to existing dataframe

In [ ]:
dat_set1['Sub4']=[9,6,7,10]
print(dat_set1)

    Sub1  Sub2  Sub3  Sub4
s1    20    10     8     9
s2    25     8    10     6
s3    27     5     3     7
s4    30     9     7    10


**To display the data from a specific row**

In [ ]:
dat_set1.loc['s2']

Sub1    25
Sub2     8
Sub3    10
Sub4     6
Name: s2, dtype: int64

In [ ]:
dat_set1.loc['s2']['Sub1']

25

In [ ]:
dat_set1.iloc[2,3]

7

In [ ]:
dat_set1.iloc[:,3]

s1     9
s2     6
s3     7
s4    10
Name: Sub4, dtype: int64

In [ ]:
dat_set1.iloc[:,0]

s1    20
s2    25
s3    27
s4    30
Name: Sub1, dtype: int64

In [ ]:
dat_set1.iloc[:,1:4]

Sub2  Sub3  Sub4
s1    10     8     9
s2     8    10     6
s3     5     3     7
s4     9     7    10

**Deletion for displaying of Specific Column**

In [ ]:
dat_set1.drop('Sub4',axis=1) #mention axis for specifying deletion from rows and columns


Sub1  Sub2  Sub3
s1    20    10     8
s2    25     8    10
s3    27     5     3
s4    30     9     7

In [ ]:
dat_set1.replace(10,12) #replaces all 10s in dataframes to 12

Sub1  Sub2  Sub3  Sub4
s1    20    12     8     9
s2    25     8    12     6
s3    27     5     3     7
s4    30     9     7    12

In [ ]:
dat_set1.replace({12:10,9:30})

Sub1  Sub2  Sub3  Sub4
s1    20    10     8    30
s2    25     8    10     6
s3    27     5     3     7
s4    30    30     7    10

In [ ]:
dat_set1.head(3)

Sub1  Sub2  Sub3  Sub4
s1    20    10     8     9
s2    25     8    10     6
s3    27     5     3     7

In [ ]:
dat_set1.tail(3)

Sub1  Sub2  Sub3  Sub4
s2    25     8    10     6
s3    27     5     3     7
s4    30     9     7    10

In [ ]:
dat_set1.sort_index(axis=0,ascending=True)

Sub1  Sub2  Sub3  Sub4
s1    20    10     8     9
s2    25     8    10     6
s3    27     5     3     7
s4    30     9     7    10

**Working with CSV file**

In [ ]:
dat_csv=pd.read_csv('/content/Data_Set.csv')

In [ ]:
print(dat_csv)

   Name of the data = Home Consumption Unnamed: 1  ...   Unnamed: 4     Unnamed: 5
0                   Unit = kW and $/kW        NaN  ...          NaN            NaN
1                                 Time     E_Plug  ...  Temperature  No. Occupants
2                                    1         24  ...          -15             12
3                                    2         17  ...          -17             12
4                                    3         16  ...          -19             12
5                                    3         16  ...          -19             12
6                                    4         16  ...          -18             12
7                                    5         16  ...          -14             12
8                                    6         16  ...          -16             12
9                                    7         19  ...          -14             12
10                                   8         22  ...          -15              9
11  